# Generated by Django 5.2.8 on 2025-11-27 15:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavouritearticle',
            unique_together={('user', 'article')},
        ),
    ]
